version: '3.8'
services:
  postgres:
    image: postgres:14.9-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - transaction-api-network
volumes:
  pgdata:

networks:
  transaction-api-network:
    driver: bridge